name: TSP Alerts Daily

on:
  schedule:
    # Run ~9:05 PM ET Tue–Sat (covers Mon–Fri trading days).
    # GitHub cron uses UTC; 01:05 UTC ≈ 9:05 PM ET (during DST it’s 8:05 PM ET).
    - cron: "30 2 * * 2-6"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Print only (no Bluesky post)"
        required: true
        default: "true"
        type: choice
        options: ["true", "false"]

permissions:
  contents: read

concurrency:
  group: tsp-alerts
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas python-dotenv requests atproto tweepy

      - name: Post TSP alert
        env:
          # Secrets you added in repo settings
          BLSKY_HANDLE: ${{ secrets.BLSKY_HANDLE }}
          BLSKY_APP_PW: ${{ secrets.BLSKY_APP_PW }}

          # Twitter (X) API secrets
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}

          # Turn OFF dry-run on the scheduled runs; honor manual input on dispatch
          DRY_RUN: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || 'false' }}

          # Optional overrides (match your .env defaults)
          WINDOW_DAYS: "30"
          POST_PREFIX: "TSP Returns"
          # FUNDS: "G Fund,F Fund,C Fund,S Fund,I Fund"  # uncomment to customize
        run: python tsp_bsky_daily.py
